name: "Plan"

on:
  pull_request:
    branches:
    - main

##TODO: Replace with YOUR azure credentials. Needed to deploy resources for workspaces with local execution mode
defaults:
  run:
    working-directory: terraform/app

permissions:
  id-token: write
  contents: read    

jobs:
  plan:
    name: Infrastructure with Plan
    runs-on: ubuntu-20.04
    environment: test

    env:
      AWS_DEFAULT_REGION: us-east-1

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::774908757058:role/github-actions-role
        role-session-name: samplerolesession
        aws-region: ${{env.AWS_DEFAULT_REGION}}

    - uses: actions/checkout@v2
      name: "Checkout self"

    - name: Configure Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_hostname: "app.terraform.io"
        cli_config_credentials_token: "${{ secrets.TFE_TOKEN }}" ## Add admin team TFE_TOKEN as GitHub secret

    - id: terraform-init
      name: Terraform init
      working-directory: 'terraform/app'
      run: terraform init

    - name: Terraform Validate
      id: terraform-validate
      working-directory: 'terraform/app'
      run: terraform validate -no-color

    - id: terraform-plan
      name: Terraform plan
      working-directory: 'terraform/app'
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color -input=false -out=tfplan -lock=false >output.txt && terraform show -no-color tfplan

    - name: Terraform Plan Status
      if: steps.terraform-plan.outcome == 'failure'
      run: cat output.txt && exit 1
