name: Test terraform-plan

on:
  - pull_request

jobs:
  no_changes:
    runs-on: ubuntu-latest
    name: No changes
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
